site_name: Fundamentos de Sistemas Operacionais
site_url: https://west7.github.io/FSO
site_author: Guilherme Westphall
site_description: Site destinado à documentação da apostila Fundamentos de sistemas operacionais.

nav:
  - Início: index.md
  - Conteúdos:
    - 1. Conceitos básicos: notes/01_conceitos_basicos.md
    - 2. Estrutura do Sistema Operacional: notes/02_estrutura_SO.md
    - 3. Processos: notes/03_processos_e_threads.md
    - 4. Gerência do processador: notes/04_gerencia_do_processador.md
    - 5. Threads: notes/05_thread.md
    - 6. Sincronização e comunicação de processos: notes/06_sincronizacao_e_comunicacao.md
    - 7. Deadlock: notes/07_deadlock.md
    - 8. Memória: notes/08_memoria.md
    - 9. Memória Virtual: notes/09_memoria_virtual.md
    - 10. Sistemas de Arquivos: notes/10_arquivos.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
      primary: black
      accent: deep purple

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro
      primary: black
      accent: deep purple
  language: pt-BR

  plugins:
  - search
  - include-markdown
  - mkdocs-material-tabs

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

        
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
